#!/usr/bin/env python3
"""Hand-emits an EpdFontData C header for a monospace Unscii bitmap font,
bypassing fontconvert.py entirely (it only accepts FreeType-loadable font
files -- TTF/OTF/BDF -- not raw pixel arrays like the ones this project's
own Unscii resizer produces).

Format matches editor/lib/EpdFont/builtinFonts/*.h exactly (verified
against EpdFontData.h and the pixel-placement math in GfxRenderer.cpp's
renderChar()/drawText()):

    screenX = x + glyph.left + glyphX
    screenY = y - glyph.top  + glyphY

Every glyph here is the *entire* fixed-size cell (true monospace, not
proportionally trimmed like the project's prose fonts), so every glyph
gets identical left=0, top=0, width=cell_w, height=cell_h, advanceX=cell_w
-- with top=0, `y` in drawText(fontId, x, y, ...) is simply the pixel row
of the *top* of the character cell, no baseline-offset math needed by
callers. 1-bit packing (not the 2-bit grayscale mode the prose fonts
use), MSB-first, ceil(width/8) bytes per row.

Usage:
    python3 emit_epdfont_header.py unscii-16.hex 8 16 2 unscii_16x32 \
        > ../../../editor/lib/EpdFont/builtinFonts/unscii_16x32.h
"""
import sys


def load_hex(path, base_w, base_h):
    glyphs = {}
    with open(path, "r", encoding="ascii") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            code_hex, data_hex = line.split(":")
            nbytes = len(data_hex) // 2
            width = 8 if nbytes == base_h else (16 if nbytes == 2 * base_h else 8)
            rows = [int(data_hex[j : j + 2], 16) for j in range(0, len(data_hex), 2)]
            glyphs[int(code_hex, 16)] = (width, rows)
    return glyphs


def scale2x(width, rows, base_h, factor):
    """axis-uniform nearest-neighbor block duplication -- exact, no artifacts"""
    out_rows = []
    for by in range(base_h):
        row_val = rows[by] if by < len(rows) else 0
        bits = [(row_val >> (width - 1 - bx)) & 1 for bx in range(width)]
        scaled_bits = []
        for b in bits:
            scaled_bits.extend([b] * factor)
        scaled_row = 0
        for b in scaled_bits:
            scaled_row = (scaled_row << 1) | b
        for _ in range(factor):
            out_rows.append((scaled_row, len(scaled_bits)))
    return out_rows


def pack_1bit_row(bits_value, width):
    nbytes = (width + 7) // 8
    padded = bits_value << (nbytes * 8 - width)
    return [(padded >> (8 * (nbytes - 1 - i))) & 0xFF for i in range(nbytes)]


def build_intervals(codepoints):
    codepoints = sorted(codepoints)
    intervals = []
    start = prev = codepoints[0]
    for cp in codepoints[1:]:
        if cp == prev + 1:
            prev = cp
            continue
        intervals.append((start, prev))
        start = prev = cp
    intervals.append((start, prev))
    return intervals


def main():
    hex_path, base_w_s, base_h_s, factor_s, name = sys.argv[1:6]
    base_w, base_h, factor = int(base_w_s), int(base_h_s), int(factor_s)
    cell_w, cell_h = base_w * factor, base_h * factor

    glyphs = load_hex(hex_path, base_w, base_h)

    codepoints = sorted(
        cp for cp in glyphs if (0x20 <= cp <= 0x7E) or (0xA0 <= cp <= 0xFF)
    )
    intervals = build_intervals(codepoints)

    bitmap_bytes = bytearray()
    glyph_entries = []  # (width, height, advanceX, left, top, dataLength, dataOffset)
    for cp in codepoints:
        width, rows = glyphs[cp]
        scaled = scale2x(width, rows, base_h, factor)
        glyph_offset = len(bitmap_bytes)
        for row_val, row_bits in scaled:
            bitmap_bytes.extend(pack_1bit_row(row_val, cell_w))
        data_length = len(bitmap_bytes) - glyph_offset
        glyph_entries.append((cell_w, cell_h, cell_w, 0, 0, data_length, glyph_offset))

    cp_to_index = {cp: i for i, cp in enumerate(codepoints)}

    out = []
    out.append("// Generated by research/fonts/tools/emit_epdfont_header.py -- do not hand-edit.")
    out.append(f"// Source: {hex_path}, {base_w}x{base_h} native, {factor}x nearest-neighbor scale to {cell_w}x{cell_h}.")
    out.append("// Public domain / CC0 (Unscii, viznut) -- see research/fonts/src/unscii-LICENSE.")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append('#include "EpdFontData.h"')
    out.append("")

    out.append(f"static const uint8_t {name}Bitmaps[{len(bitmap_bytes)}] = {{")
    for i in range(0, len(bitmap_bytes), 16):
        chunk = bitmap_bytes[i : i + 16]
        out.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    out.append("};")
    out.append("")

    out.append(f"static const EpdGlyph {name}Glyphs[{len(glyph_entries)}] = {{")
    for w, h, adv, left, top, dlen, doff in glyph_entries:
        out.append(f"    {{ {w}, {h}, {adv}, {left}, {top}, {dlen}, {doff} }},")
    out.append("};")
    out.append("")

    out.append(f"static const EpdUnicodeInterval {name}Intervals[{len(intervals)}] = {{")
    running_offset = 0
    for first, last in intervals:
        out.append(f"    {{ 0x{first:X}, 0x{last:X}, {running_offset} }},")
        running_offset += last - first + 1
    out.append("};")
    out.append("")

    out.append(f"static const EpdFontData {name} = {{")
    out.append(f"    {name}Bitmaps,")
    out.append(f"    {name}Glyphs,")
    out.append(f"    {name}Intervals,")
    out.append(f"    {len(intervals)},")
    out.append(f"    {cell_h},  // advanceY")
    out.append(f"    {cell_h},  // ascender")
    out.append(f"    0,   // descender")
    out.append(f"    false,  // is2Bit")
    out.append("};")

    print("\n".join(out))

    # sanity check to stderr
    for first, last in intervals:
        for cp in range(first, last + 1):
            assert cp in cp_to_index, f"gap at U+{cp:04X}"
    print(f"// OK: {len(codepoints)} glyphs, {len(intervals)} interval(s), "
          f"{len(bitmap_bytes)} bitmap bytes", file=sys.stderr)


if __name__ == "__main__":
    main()
